name: Compiling with Pyinstaller

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "requirements*.txt"
      - run: |
          pip install -r requirements.txt
          pip install -r requirements-dist.txt
      - name: Run Pyinstaller
        run: |
          pyinstaller run_gui.py
      - name: Compress binary files
        env:
          THIS_OS: ${{ matrix.os }}
        run: zip -r run_gui-"$THIS_OS".zip dist/run_gui/
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
              run_gui-*.zip
              LICENSE
